# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: black_panther/messages/bodystyle.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "black_panther.messages.BodyStyle" do
    optional :description, :string, 1
  end
end

module BlackPanther
  module Messages
    BodyStyle = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.BodyStyle").msgclass
  end
end
