# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: black_panther/messages/engine.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "black_panther.messages.Engine" do
    optional :name, :string, 1
  end
end

module BlackPanther
  module Messages
    Engine = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.Engine").msgclass
  end
end
