# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: black_panther/messages/fuel_group.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "black_panther.messages.FuelGroup" do
    optional :description, :enum, 1, "black_panther.messages.FuelGroup.Descriptions"
  end
  add_enum "black_panther.messages.FuelGroup.Descriptions" do
    value :PETROL, 0
    value :DIESEL, 1
    value :ELECTRIC, 2
    value :HYBRID, 3
  end
end

module BlackPanther
  module Messages
    FuelGroup = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.FuelGroup").msgclass
    FuelGroup::Descriptions = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.FuelGroup.Descriptions").enummodule
  end
end
