# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: black_panther/messages/manufacturer.proto

require 'google/protobuf'

require 'black_panther/messages/model_group_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "black_panther.messages.Manufacturer" do
    optional :name, :string, 1
    repeated :model_group, :message, 2, "black_panther.messages.ModelGroup"
  end
end

module BlackPanther
  module Messages
    Manufacturer = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.Manufacturer").msgclass
  end
end
