# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: black_panther/messages/model.proto

require 'google/protobuf'

require 'black_panther/messages/bodystyle_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "black_panther.messages.Model" do
    optional :name, :string, 1
    optional :bodystyle, :message, 2, "black_panther.messages.BodyStyle"
  end
end

module BlackPanther
  module Messages
    Model = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.Model").msgclass
  end
end
