# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: black_panther/messages/option.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "black_panther.messages.Option" do
    optional :description, :string, 1
    optional :price, :double, 2
  end
end

module BlackPanther
  module Messages
    Option = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.Option").msgclass
  end
end
