# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: black_panther/messages/residual_value.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "black_panther.messages.ResidualValue" do
    optional :term, :string, 1
    optional :mileage, :int64, 2
    optional :price, :double, 3
  end
end

module BlackPanther
  module Messages
    ResidualValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.ResidualValue").msgclass
  end
end
