# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: black_panther/messages/transmission_group.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "black_panther.messages.TransmissionGroup" do
    optional :name, :enum, 1, "black_panther.messages.TransmissionGroup.TranmissionTypes"
  end
  add_enum "black_panther.messages.TransmissionGroup.TranmissionTypes" do
    value :MANUAL, 0
    value :AUTO, 1
  end
end

module BlackPanther
  module Messages
    TransmissionGroup = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.TransmissionGroup").msgclass
    TransmissionGroup::TranmissionTypes = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.TransmissionGroup.TranmissionTypes").enummodule
  end
end
