# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: black_panther/messages/vehicle.proto

require 'google/protobuf'

require 'black_panther/messages/engine_pb'
require 'black_panther/messages/fuel_group_pb'
require 'black_panther/messages/transmission_group_pb'
require 'black_panther/messages/manufacturer_pb'
require 'black_panther/messages/model_group_pb'
require 'black_panther/messages/model_pb'
require 'black_panther/messages/option_pb'
require 'black_panther/messages/residual_value_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "black_panther.messages.Vehicle" do
    optional :price, :double, 1
    optional :kee_id, :string, 2
    optional :cap_id, :string, 3
    optional :co2, :string, 4
    optional :engine, :message, 5, "black_panther.messages.Engine"
    optional :fuel_group, :message, 6, "black_panther.messages.FuelGroup"
    optional :transmission_group, :message, 7, "black_panther.messages.TransmissionGroup"
    optional :manufacturer, :message, 8, "black_panther.messages.Manufacturer"
    optional :model_group, :message, 9, "black_panther.messages.ModelGroup"
    optional :model, :message, 10, "black_panther.messages.Model"
    repeated :option, :message, 11, "black_panther.messages.Option"
    repeated :residual_value, :message, 12, "black_panther.messages.ResidualValue"
  end
end

module BlackPanther
  module Messages
    Vehicle = Google::Protobuf::DescriptorPool.generated_pool.lookup("black_panther.messages.Vehicle").msgclass
  end
end
